wcs_coav_planemodel:
    resource: "@WCSCoavBundle/Resources/config/routing/planemodel.yml"
    prefix:   /planemodel

wcs_coav_homepage:
    path:     /
    defaults: { _controller: WCSCoavBundle:Default:index }

wcs_coav_flight:
    resource: "@WCSCoavBundle/Resources/config/routing/flight.yml"
    prefix:   /flight

wcs_coav_reservation:
    resource: "@WCSCoavBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation