services:
#    wcs_coav.example:
#        class: WCS\CoavBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


services:
    app.admin.terrain:
        class: WCS\CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu Terrain", label: "Terrain" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Terrain
            - ~

    app.admin.flight:
        class: WCS\CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu Flight", label: "Flight" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Flight
            - ~

    app.admin.planeModel:
        class: WCS\CoavBundle\Admin\PlaneModelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu Plane Model", label: "Plane Model" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\PlaneModel
            - ~


    app.admin.reservation:
        class: WCS\CoavBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu Reservation", label: "Reservation" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Reservation
            - ~

    app.admin.user:
        class: WCS\CoavBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu User", label: "User" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\User
            - ~