wcs_coav:
    resource: "@WCSCoavBundle/Resources/config/routing.yml"
    prefix:   /

quetesymfony:
    resource: "@QuetesymfonyBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
