WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        freeSeats:
            type: integer
        takeofTime:
            type: datetime

    lifecycleCallbacks: {  }


    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures
        pilot:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: pilots
        arrival:
            targetEntity: WCS\CoavBundle\Entity\PlaneModel
            inversedBy: arrivals
        departure:
            targetEntity: WCS\CoavBundle\Entity\Reservation
            inversedBy: departures


