<?php

namespace WCS\CoavBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlaneModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneModelRepository extends EntityRepository
{
}
