<?php

namespace WCS\CoavBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrainRepository extends EntityRepository
{
}
